insert into Customer (name, address) values ('chris', '666 satin rd');
insert into Customer (name, address) values ('austin', '123 happy st');
insert into Customer (name, address) values ('conner', '45 lame st');
insert into Customer (name, address) values ('lawrence', '404 error rd');
insert into Customer (name, address) values ('bill', '101 excellent blvd');
insert into Customer (name, address) values ('ted', '101 excellent blvd');
insert into Customer (name, address) values ('bob', '78 builder st');
insert into Customer (name, address) values ('will', '752 testament rd');
insert into Customer (name, address) values ('bob', '554 builder rd');
insert into Customer (name, address) values ('kevin', '489 reddit dr');

insert into car (year, make, model, cust_id) values (2019, 'dodge', 'viper', 1);
insert into car (year, make, model, cust_id) values (1746, 'dodge', 'charger', 2);
insert into car (year, make, model, cust_id) values (2011, 'bmw', 'm3', 6);
insert into car (year, make, model, cust_id) values (2000, 'ford', 'focus' 9);
insert into car (year, make, model, cust_id) values (2008, 'ford', 'thunderbird' 4);
insert into car (year, make, model, cust_id) values (1994, 'honda', 'accord', 3);
insert into car (year, make, model, cust_id) values (2000, 'ford', 'focus', 7);
insert into car (year, make, model, cust_id) values (2007, 'honda', 'accord', 5);
insert into car (year, make, model, cust_id) values (2018, 'bmw', '525i', 10);
insert into car (year, make, model, cust_id) values (2020, 'audi', 'gti', 8);
insert into car (year, make, model, cust_id) values (2015, 'bugatti', 'veyron' 1);
insert into car (year, make, model, cust_id) values (2020, 'bently', 'continental gt', 2);

insert into Owns (cust_id, car_id) values (1, 1);
insert into Owns (cust_id, car_id) values (2, 2);
insert into Owns (cust_id, car_id) values (3, 6);
insert into Owns (cust_id, car_id) values (4, 5);
insert into Owns (cust_id, car_id) values (5, 8);
insert into Owns (cust_id, car_id) values (6, 3);
insert into Owns (cust_id, car_id) values (7, 7);
insert into Owns (cust_id, car_id) values (8, 10);
insert into Owns (cust_id, car_id) values (9, 4);
insert into Owns (cust_id, car_id) values (10, 9);
insert into Owns (cust_id, car_id) values (1, 11);
insert into Owns (cust_id, car_id) values (2, 12);

insert into Phonenumbers (phonenumber, cust_id) values('123-456-7899', 1);
insert into Phonenumbers (phonenumber, cust_id) values('998-765-4321', 2);
insert into Phonenumbers (phonenumber, cust_id) values('555-555-5555', 3);
insert into Phonenumbers (phonenumber, cust_id) values('123-456-7769', 4);
insert into Phonenumbers (phonenumber, cust_id) values('763-951-4679', 5);
insert into Phonenumbers (phonenumber, cust_id) values('789-555-2587', 6);
insert into Phonenumbers (phonenumber, cust_id) values('999-999-9999', 7);
insert into Phonenumbers (phonenumber, cust_id) values('111-222-4444', 8);
insert into Phonenumbers (phonenumber, cust_id) values('696-969-6969', 9);
insert into Phonenumbers (phonenumber, cust_id) values('456-777-1234', 10);
insert into Phonenumbers (phonenumber, cust_id) values('666-666-6666', 1);
insert into Phonenumbers (phonenumber, cust_id) values('555-727-8215', 8);
insert into Phonenumbers (phonenumber, cust_id) values('907-709-8456', 4);
insert into Phonenumbers (phonenumber, cust_id) values('333-489-1212', 4);